import {
  TAX_ON_SALES_PRICE,
  TAX_ON_TOTAL_LEASE_PAYMENT,
} from "../src/constants";

export const DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT = {
  make: "Toyota",
  msrp: 23000,
  sellingPrice: 21000,
  rv: 13110,
  isRVPercent: false,
  mf: 0.00125,
  leaseTerm: 36,
  salesTax: 10.25,
  totalFees: 1200,
  rebates: 500,
};

export const DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT = {
  make: "Toyota",
  msrp: 23000,
  sellingPrice: 21000,
  rv: 13110,
  isRVPercent: false,
  mf: 0.00125,
  leaseTerm: 36,
  salesTax: 10.25,
  totalFees: 1200,
  rebates: 500,
  rebates: 0,
  downPayment: 1700,
};

export const DUMMY_LEASE_WITH_PERCENTAGE_RV = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  rv: 57,
  isRVPercent: true,
};

export const RV_VALUE = 13110;
export const RV_PERCENTAGE = 57;
export const ACQUISITION_FEE_TOYOTA = 650;
export const DISPOSITION_FEE_TOYOTA = 350;

export const WHEN_TAX_ON_MONTHLY_PAYMENT = {
  APR: 3,
  OFF_MSRP: 8.7,
  PAYMENT_ZERO_DOWN: 331.84,
  PAYMENT_WITH_DOWN: 293.44,
  MSRP_PERCENTAGE: 1.44,
  PAYMENT_ZERO_DOWN_PRE_TAX: 300.99,
  TOTAL_LEASE_COST_ZERO_DOWN: 13619.36,
  TOTAL_LEASE_COST_WITH_DOWN: 14111.07,
};

export const DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_SALES_PRICE = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TAX_ON_SALES_PRICE,
};

export const DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_SALES_PRICE = {
  ...DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TAX_ON_SALES_PRICE,
};

export const WHEN_TAX_ON_SALES_PRICE = {
  PAYMENT_ZERO_DOWN: 300.99,
  PAYMENT_WITH_DOWN: 266.16,
  MSRP_PERCENTAGE: 1.31,
  PAYMENT_ZERO_DOWN_PRE_TAX: 300.99,
  TOTAL_LEASE_COST_ZERO_DOWN: 14538.2,
  TOTAL_LEASE_COST_WITH_DOWN: 14984.2,
};

export const DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_LEASE_PAYMENT = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TAX_ON_TOTAL_LEASE_PAYMENT,
};

export const DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_LEASE_PAYMENT = {
  ...DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TAX_ON_TOTAL_LEASE_PAYMENT,
};

export const WHEN_TAX_ON_LEASE_PAYMENT = {
  PAYMENT_ZERO_DOWN: 300.99,
  PAYMENT_WITH_DOWN: 266.16,
  MSRP_PERCENTAGE: 1.31,
  PAYMENT_ZERO_DOWN_PRE_TAX: 300.99,
  TOTAL_LEASE_COST_ZERO_DOWN: 12606.18,
  TOTAL_LEASE_COST_WITH_DOWN: 13222.86,
};
