export const TAX_ON_MONTHLY_PAYMENT = 1;
export const TAX_ON_SALES_PRICE = 2;
export const TAX_ON_TOTAL_LEASE_PAYMENT = 3;

export const MAKES = [
  { id: 1, displayName: "Acura" },
  { id: 2, displayName: "Alfa Romeo" },
  { id: 3, displayName: "Audi" },
  { id: 4, displayName: "Bmw" },
  { id: 5, displayName: "Buick" },
  { id: 6, displayName: "Cadillac" },
  { id: 7, displayName: "Chevrolet" },
  { id: 8, displayName: "Chrysler" },
  { id: 9, displayName: "Dodge" },
  { id: 10, displayName: "Fiat" },
  { id: 11, displayName: "Ford" },
  { id: 12, displayName: "Genesis" },
  { id: 13, displayName: "GMC" },
  { id: 14, displayName: "Honda" },
  { id: 15, displayName: "Hyundai" },
  { id: 16, displayName: "Infiniti" },
  { id: 17, displayName: "Jaguar" },
  { id: 18, displayName: "Jeep" },
  { id: 19, displayName: "Kia" },
  { id: 20, displayName: "land rover" },
  { id: 21, displayName: "Lexus" },
  { id: 22, displayName: "Lincoln" },
  { id: 23, displayName: "Mini" },
  { id: 24, displayName: "Mazda" },
  { id: 25, displayName: "Mercedes benz" },
  { id: 26, displayName: "Mitsubishi" },
  { id: 27, displayName: "Nissan" },
  { id: 28, displayName: "Ram" },
  { id: 29, displayName: "Scion" },
  { id: 30, displayName: "Smart" },
  { id: 31, displayName: "Subaru" },
  { id: 32, displayName: "Tesla" },
  { id: 33, displayName: "Toyota" },
  { id: 34, displayName: "Volkswagen" },
  { id: 35, displayName: "Volvo" },
];
export const MANUFACTURER_FEES = [
  { makeId: 1, acquisitionFee: 595 },
  { makeId: 2, acquisitionFee: 595, dispositionFee: 395 },
  { makeId: 3, acquisitionFee: 895, dispositionFee: 495 },
  {
    makeId: 4,
    acquisitionFee: 925,
    dispositionFee: 350,
    mfReductionUnit: 0.00007,
  },
  { makeId: 5, acquisitionFee: 650, dispositionFee: 495 },
  { makeId: 6, acquisitionFee: 650, dispositionFee: 595 },
  { makeId: 7, acquisitionFee: 650, dispositionFee: 395 },
  { makeId: 8, acquisitionFee: 595, dispositionFee: 395 },
  { makeId: 9, acquisitionFee: 595, dispositionFee: 395 },
  { makeId: 10, acquisitionFee: 595, dispositionFee: 395 },
  { makeId: 11, acquisitionFee: 645, dispositionFee: 395 },
  { makeId: 12, acquisitionFee: 595, dispositionFee: 400 },
  { makeId: 13, acquisitionFee: 650, dispositionFee: 495 },
  { makeId: 14, acquisitionFee: 595, dispositionFee: 0 },
  { makeId: 15, acquisitionFee: 595, dispositionFee: 400 },
  {
    makeId: 16,
    acquisitionFee: 700,
    dispositionFee: 395,
    mfReductionUnit: 0.0001,
  },
  { makeId: 17, acquisitionFee: 895, dispositionFee: 300 },
  { makeId: 18, acquisitionFee: 795, dispositionFee: 395 },
  { makeId: 19, acquisitionFee: 595, dispositionFee: 400 },
  { makeId: 20, acquisitionFee: 895, dispositionFee: 300 },
  {
    makeId: 21,
    acquisitionFee: 795,
    dispositionFee: 350,
    mfReductionUnit: 0.00008,
  },
  { makeId: 22, acquisitionFee: 645, dispositionFee: 0 },
  { makeId: 23, acquisitionFee: 925, dispositionFee: 350 },
  { makeId: 24, acquisitionFee: 595, dispositionFee: 300 },
  {
    makeId: 25,
    acquisitionFee: 795,
    dispositionFee: 595,
    mfReductionUnit: 0.00007,
  },
  { makeId: 26, acquisitionFee: 595, dispositionFee: 0 },
  { makeId: 27, acquisitionFee: 650, dispositionFee: 395 },
  { makeId: 28, acquisitionFee: 595, dispositionFee: 395 },
  {
    makeId: 29,
    acquisitionFee: 650,
    dispositionFee: 350,
    mfReductionUnit: 0.00008,
  },
  { makeId: 30, acquisitionFee: 295, dispositionFee: 395 },
  { makeId: 31, acquisitionFee: 595, dispositionFee: 300 },
  { makeId: 32, acquisitionFee: 695, dispositionFee: 395 },
  {
    makeId: 33,
    acquisitionFee: 650,
    dispositionFee: 350,
    mfReductionUnit: 0.00008,
  },
  { makeId: 34, acquisitionFee: 675, dispositionFee: 395 },
  { makeId: 35, acquisitionFee: 995, dispositionFee: 350 },
];
